refactor: add config args, adopt e2e
flowup/quality-metrics-cli pull request #113
Opened 2023-10-15 22:57 UTC by BioPhoton

2023-10-16 08:37 UTC, ChristopherPHolder approved these changes

2023-10-16 09:02 UTC, matejchalk requested changes

2023-10-16 09:02 UTC, matejchalk commented on packages/cli/src/lib/implementation/core-config-options.ts
>      },
- What's CSV in this context? :raised_eyebrow: 
- It's not the name, but the slug, that could be misleading.
- The description formatting is inconsistent, `--upload.organization` and `--upload.project` descriptions aren't capitalized like the others.

```suggestion
    // upload
    'upload.organization': {
      describe: 'Organization slug from portal',
      type: 'string',
    },
    'upload.project': {
      describe: 'Project slug from portal',
      type: 'string',
    },
```

2023-10-16 09:02 UTC, matejchalk commented on packages/cli/src/lib/implementation/core-config-options.ts
> +      describe: 'apiKey for the portal server',
```suggestion
      describe: 'API key for the portal server',
```

2023-10-17 09:02 UTC, matejchalk approved these changes

2023-10-17 09:14 UTC, merged